### Get all persons
GET http://localhost:3001/api/persons

### Get info
GET http://localhost:3001/info

### Get a single person
GET http://localhost:3001/api/persons/6767fb09a4658f8f58074903

### Delete a person
DELETE http://localhost:3001/api/persons/6767fb09a4658f8f58074903

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "New Person",
  "number": "123-456789"
}

### Error handling: Missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-456789"
}

### Error handling: Missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "New Person2"
}

### Error handling: Name must be unique
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123-456789"
}
